name: Clojure CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    services:
      faktory:
        image: contribsys/faktory:1.1.0
        ports:
          - 7419:7419

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test
